name: GO linting

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - 'packages/backend/**'
      - 'packages/client/**'
      - 'packages/collector-kvg/**'
      - 'packages/pub-sub-porto/**'
  pull_request:
    paths:
      - 'packages/backend/**'
      - 'packages/client/**'
      - 'packages/collector-kvg/**'
      - 'packages/pub-sub-porto/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint backend
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.40.1
          working-directory: packages/backend

      - name: golangci-lint client
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.40.1
          working-directory: packages/client

      - name: golangci-lint pub-sub-proto
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.40.1
          working-directory: packages/pub-sub-proto

      - name: golangci-lint collector-kvg
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.40.1
          working-directory: packages/pub-sub-proto